<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reports - IEMS</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="dashboard-container">
        <nav class="sidebar">
            <h3>Reports Portal</h3>
            <ul class="sidebar-menu">
                <li><a href="admin-dashboard.php">Dashboard</a></li>
                <li><a href="reports.php" class="active">Reports</a></li>
                <li><a href="home.php" onclick="logout()">Logout</a></li>
            </ul>
        </nav>

        <main class="dashboard-content">
            <h1>Reports & Analytics</h1>
            
            <div class="card">
                <h3>Generate Reports</h3>
                <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 2rem;">
                    <div class="card" style="background: #f8f9fa;">
                        <h4>Event Reports</h4>
                        <p>Generate detailed reports for events</p>
                        <select class="form-control mb-1">
                            <option>Select Event</option>
                            <option>Code Marathon</option>
                            <option>Classical Dance Competition</option>
                            <option>All Events</option>
                        </select>
                        <button class="btn">Generate Report</button>
                    </div>
                    
                    <div class="card" style="background: #f8f9fa;">
                        <h4>Participation Reports</h4>
                        <p>Student participation statistics</p>
                        <select class="form-control mb-1">
                            <option>Select Department</option>
                            <option>Computer Science</option>
                            <option>Information Technology</option>
                            <option>All Departments</option>
                        </select>
                        <button class="btn">Generate Report</button>
                    </div>
                    
                    <div class="card" style="background: #f8f9fa;">
                        <h4>Performance Reports</h4>
                        <p>Event performance and results analysis</p>
                        <select class="form-control mb-1">
                            <option>Select Academic Year</option>
                            <option>2024-25</option>
                            <option>2023-24</option>
                        </select>
                        <button class="btn">Generate Report</button>
                    </div>
                    
                    <div class="card" style="background: #f8f9fa;">
                        <h4>Faculty Reports</h4>
                        <p>Faculty coordination and evaluation reports</p>
                        <select class="form-control mb-1">
                            <option>Select Faculty</option>
                            <option>Dr. Smith Johnson</option>
                            <option>Prof. Sarah Wilson</option>
                            <option>All Faculty</option>
                        </select>
                        <button class="btn">Generate Report</button>
                    </div>
                </div>
            </div>

            <div class="card">
                <h3>Quick Statistics</h3>
                <div class="stats-grid">
                    <div class="stat-card">
                        <div class="stat-number">25</div>
                        <div class="stat-label">Total Events</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-number">456</div>
                        <div class="stat-label">Total Registrations</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-number">89%</div>
                        <div class="stat-label">Completion Rate</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-number">4.2</div>
                        <div class="stat-label">Avg Rating</div>
                    </div>
                </div>
            </div>

            <div class="card">
                <h3>Recent Reports</h3>
                <div class="table-container">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Report Name</th>
                                <th>Type</th>
                                <th>Generated By</th>
                                <th>Date</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Monthly Event Summary - February 2025</td>
                                <td>Event Report</td>
                                <td>Admin</td>
                                <td>March 1, 2025</td>
                                <td>
                                    <button class="btn" onclick="downloadReport(1)">Download</button>
                                    <button class="btn btn-secondary" onclick="viewReport(1)">View</button>
                                </td>
                            </tr>
                            <tr>
                                <td>Student Participation Analysis</td>
                                <td>Participation Report</td>
                                <td>Admin</td>
                                <td>February 28, 2025</td>
                                <td>
                                    <button class="btn" onclick="downloadReport(2)">Download</button>
                                    <button class="btn btn-secondary" onclick="viewReport(2)">View</button>
                                </td>
                            </tr>
                            <tr>
                                <td>Faculty Performance Report</td>
                                <td>Faculty Report</td>
                                <td>Admin</td>
                                <td>February 25, 2025</td>
                                <td>
                                    <button class="btn" onclick="downloadReport(3)">Download</button>
                                    <button class="btn btn-secondary" onclick="viewReport(3)">View</button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </main>
    </div>

    <script>
        function downloadReport(id) {
            alert('Report ' + id + ' downloaded successfully!');
        }
        
        function viewReport(id) {
            alert('Viewing report ' + id);
        }
        
        function logout() {
            localStorage.removeItem('userLoggedIn');
            localStorage.removeItem('userRole');
            window.location.href = 'home.php';
        }
    </script>
</body>
</html>
